In [5]:
import polars as pl
import seaborn as sns
from sqlalchemy import create_engine, URL
import dotenv

In [6]:
env = dotenv.find_dotenv()
env_values = dotenv.dotenv_values(env)
env_values

OrderedDict([('POSTGRES_PWD', 'R3GG13_LU!')])

In [7]:
url = URL.create(
    drivername="postgresql+psycopg2",
    username="postgres",
    password=env_values["POSTGRES_PWD"],
    host="localhost",
    port=5432,
    database="retail"
)

engine = create_engine(url)

conn = engine.connect()

inventory = pl.read_database(
    query="""
        SELECT * FROM inventory
    """,
    connection=conn
)

conn.close()

inventory.head(50)

shape: (50, 14)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sku      ┆ product_n ┆ category  ┆ store_loc ┆ … ┆ unit_reta ┆ out_of_st ┆ expiry_da ┆ markdown_ │
│ ---      ┆ ame       ┆ ---       ┆ ation     ┆   ┆ il_price_ ┆ ock_days_ ┆ te        ┆ flag      │
│ str      ┆ ---       ┆ str       ┆ ---       ┆   ┆ usd       ┆ 30d       ┆ ---       ┆ ---       │
│          ┆ str       ┆           ┆ str       ┆   ┆ ---       ┆ ---       ┆ str       ┆ str       │
│          ┆           ┆           ┆           ┆   ┆ decimal[3 ┆ i64       ┆           ┆           │
│          ┆           ┆           ┆           ┆   ┆ 8,2]      ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SKU-1128 ┆ Johnsonvi ┆ Meat      ┆ East      ┆ … ┆ 29.20     ┆ 16        ┆ 2025-01-1 ┆ 0         │
│          ┆ lle Mild  ┆           ┆ Plaza     ┆   ┆           ┆           ┆ 8         ┆           │
│          ┆ Italian   ┆           ┆           ┆   ┆           ┆           ┆ 11:40:23  ┆           │
│          ┆ Saus…     ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ SKU-1070 ┆ DiGiorno  ┆ Frozen    ┆ West      ┆ … ┆ 44.50     ┆ 5         ┆ 2026-04-0 ┆ TRUE      │
│          ┆ Rising    ┆           ┆ Corner    ┆   ┆           ┆           ┆ 5         ┆           │
│          ┆ Crust     ┆           ┆           ┆   ┆           ┆           ┆ 18:12:03  ┆           │
│          ┆ Pepperon… ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ SKU-1109 ┆ Celery    ┆ Prodce    ┆ West Main ┆ … ┆ 4.92      ┆ 2         ┆ 2024-06-1 ┆ y         │
│          ┆ Bunch     ┆           ┆ St        ┆   ┆           ┆           ┆ 5         ┆           │
│          ┆ Each      ┆           ┆           ┆   ┆           ┆           ┆ 12:04:55  ┆           │
│ SKU-1178 ┆ Pepto-Bis ┆ Personal  ┆ East Main ┆ … ┆ 34.34     ┆ 23        ┆ 2024-11-1 ┆ N         │
│          ┆ mol       ┆ Care      ┆ St        ┆   ┆           ┆           ┆ 1         ┆           │
│          ┆ Original  ┆           ┆           ┆   ┆           ┆           ┆ 02:42:35  ┆           │
│          ┆ 12oz      ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ SKU-1074 ┆ Hot       ┆ Frozen    ┆ Nrth Main ┆ … ┆ 45.29     ┆ 27        ┆ 2025-04-0 ┆ N         │
│          ┆ Pockets   ┆           ┆ St        ┆   ┆           ┆           ┆ 7         ┆           │
│          ┆ Ham       ┆           ┆           ┆   ┆           ┆           ┆ 13:37:12  ┆           │
│          ┆ Cheese    ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 9oz       ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ SKU-1103 ┆ Roma      ┆ produce   ┆ North     ┆ … ┆ 9.10      ┆ 18        ┆ 2025-03-1 ┆ TRUE      │
│          ┆ Tomatoes  ┆           ┆ Corner    ┆   ┆           ┆           ┆ 2         ┆           │
│          ┆ 1lb       ┆           ┆           ┆   ┆           ┆           ┆ 20:26:49  ┆           │
│ SKU-1134 ┆ Hebrew    ┆ Meat      ┆ West Main ┆ … ┆ 39.79     ┆ 23        ┆ 2025-12-0 ┆ N         │
│          ┆ National  ┆           ┆ St        ┆   ┆           ┆           ┆ 7         ┆           │
│          ┆ Beef      ┆           ┆           ┆   ┆           ┆           ┆ 07:37:38  ┆           │
│          ┆ Franks    ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 11…       ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ SKU-1068 ┆ Vital     ┆ Dairy     ┆ West      ┆ … ┆ 27.85     ┆ 22        ┆ 2026-04-2 ┆ FALSE     │
│          ┆ Farms     ┆           ┆ Plaza     ┆   ┆           ┆           ┆ 2         ┆           │
│          ┆ Pasture   ┆           ┆           ┆   ┆           ┆           ┆ 07:38:38  ┆           │
│          ┆ Raised    ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ Egg…      ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ SKU-1056 ┆ Kraft     ┆ Dairy     ┆ West      ┆ … ┆ 22.59     ┆ 15        ┆ 2026-03-2 ┆ TRUE      │
│          ┆ Singles   ┆           ┆ Corner    ┆   ┆           ┆           ┆ 5         ┆           │
│          ┆ American  ┆           ┆           ┆   ┆           ┆           ┆ 14:30:50  ┆           │
│          ┆ 16 slic…  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ SKU-1194 ┆ Mega      ┆ Lottery   ┆ North     ┆ … ┆ 45.86     ┆ 22        ┆ null      ┆ n         │
│          ┆ Millions  ┆           ┆ Corner    ┆   ┆           ┆           ┆           ┆           │
│          ┆ $2 Ticket ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [8]:
inventory.select(['sku']).null_count()

shape: (1, 1)
┌─────┐
│ sku │
│ --- │
│ u32 │
╞═════╡
│ 0   │
└─────┘